name: Tests

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set directory permissions
      run: chmod -R 777 .

    - name: Build the docker-compose stack
      run: docker-compose up -d

    - name: Check running containers
      run: docker ps -a

    - name: Check docker logs
      run: docker-compose logs web

    - name: Run composer setup
      run: docker-compose exec -T web composer setup-ci

    - name: Run phpcs
      run: docker-compose exec -T web vendor/bin/phpcs

    - name: Run phpstan
      run: docker-compose exec -T web vendor/bin/phpstan analyse --no-progress

    - name: Run grumphp
      run: docker-compose exec -T web vendor/bin/grumphp run --tasks=yamllint

    - name: Run phpunit
      run: docker-compose exec -T web vendor/bin/phpunit -c phpunit.xml.dist

    - name: Run clover coverage tests
      run: docker-compose exec -T web vendor/bin/grumphp run --tasks=clover_coverage
